import { toCamelCase } from "./Utils";

type LeaderboardKey = {
	name: string;
	value: string;
	short?: string;
	explanation?: string;
};
export const keys: LeaderboardKey[] = [
	// Ratings pattern: SkyWars_skywars_rating_{season}_{year}_{type}
	// 2018 (S3–S12)
	{ name: "Ranked Season 24", short: "Position", value: "SkyWars_skywars_rating_3_18_position" },
	{ name: "Ranked Season 24", short: "Rating", value: "SkyWars_skywars_rating_3_18_rating" },
	{ name: "Ranked Season 25", short: "Position", value: "SkyWars_skywars_rating_4_18_position" },
	{ name: "Ranked Season 25", short: "Rating", value: "SkyWars_skywars_rating_4_18_rating" },
	{ name: "Ranked Season 26", short: "Position", value: "SkyWars_skywars_rating_5_18_position" },
	{ name: "Ranked Season 26", short: "Rating", value: "SkyWars_skywars_rating_5_18_rating" },
	{ name: "Ranked Season 27", short: "Position", value: "SkyWars_skywars_rating_6_18_position" },
	{ name: "Ranked Season 27", short: "Rating", value: "SkyWars_skywars_rating_6_18_rating" },
	{ name: "Ranked Season 28", short: "Position", value: "SkyWars_skywars_rating_7_18_position" },
	{ name: "Ranked Season 28", short: "Rating", value: "SkyWars_skywars_rating_7_18_rating" },
	{ name: "Ranked Season 29", short: "Position", value: "SkyWars_skywars_rating_8_18_position" },
	{ name: "Ranked Season 29", short: "Rating", value: "SkyWars_skywars_rating_8_18_rating" },
	{ name: "Ranked Season 30", short: "Position", value: "SkyWars_skywars_rating_9_18_position" },
	{ name: "Ranked Season 30", short: "Rating", value: "SkyWars_skywars_rating_9_18_rating" },
	{ name: "Ranked Season 31", short: "Position", value: "SkyWars_skywars_rating_10_18_position" },
	{ name: "Ranked Season 31", short: "Rating", value: "SkyWars_skywars_rating_10_18_rating" },
	{ name: "Ranked Season 32", short: "Position", value: "SkyWars_skywars_rating_11_18_position" },
	{ name: "Ranked Season 32", short: "Rating", value: "SkyWars_skywars_rating_11_18_rating" },
	{ name: "Ranked Season 33", short: "Position", value: "SkyWars_skywars_rating_12_18_position" },
	{ name: "Ranked Season 33", short: "Rating", value: "SkyWars_skywars_rating_12_18_rating" },

	// 2019 (S1–S12)
	{ name: "Ranked Season 34", short: "Position", value: "SkyWars_skywars_rating_1_19_position" },
	{ name: "Ranked Season 34", short: "Rating", value: "SkyWars_skywars_rating_1_19_rating" },
	{ name: "Ranked Season 35", short: "Position", value: "SkyWars_skywars_rating_2_19_position" },
	{ name: "Ranked Season 35", short: "Rating", value: "SkyWars_skywars_rating_2_19_rating" },
	{ name: "Ranked Season 36", short: "Position", value: "SkyWars_skywars_rating_3_19_position" },
	{ name: "Ranked Season 36", short: "Rating", value: "SkyWars_skywars_rating_3_19_rating" },
	{ name: "Ranked Season 37", short: "Position", value: "SkyWars_skywars_rating_4_19_position" },
	{ name: "Ranked Season 37", short: "Rating", value: "SkyWars_skywars_rating_4_19_rating" },
	{ name: "Ranked Season 38", short: "Position", value: "SkyWars_skywars_rating_5_19_position" },
	{ name: "Ranked Season 38", short: "Rating", value: "SkyWars_skywars_rating_5_19_rating" },
	{ name: "Ranked Season 39", short: "Position", value: "SkyWars_skywars_rating_6_19_position" },
	{ name: "Ranked Season 39", short: "Rating", value: "SkyWars_skywars_rating_6_19_rating" },
	{ name: "Ranked Season 40", short: "Position", value: "SkyWars_skywars_rating_7_19_position" },
	{ name: "Ranked Season 40", short: "Rating", value: "SkyWars_skywars_rating_7_19_rating" },
	{ name: "Ranked Season 41", short: "Position", value: "SkyWars_skywars_rating_8_19_position" },
	{ name: "Ranked Season 41", short: "Rating", value: "SkyWars_skywars_rating_8_19_rating" },
	{ name: "Ranked Season 42", short: "Position", value: "SkyWars_skywars_rating_9_19_position" },
	{ name: "Ranked Season 42", short: "Rating", value: "SkyWars_skywars_rating_9_19_rating" },
	{ name: "Ranked Season 43", short: "Position", value: "SkyWars_skywars_rating_10_19_position" },
	{ name: "Ranked Season 43", short: "Rating", value: "SkyWars_skywars_rating_10_19_rating" },
	{ name: "Ranked Season 44", short: "Position", value: "SkyWars_skywars_rating_11_19_position" },
	{ name: "Ranked Season 44", short: "Rating", value: "SkyWars_skywars_rating_11_19_rating" },
	{ name: "Ranked Season 45", short: "Position", value: "SkyWars_skywars_rating_12_19_position" },
	{ name: "Ranked Season 45", short: "Rating", value: "SkyWars_skywars_rating_12_19_rating" },

	// 2020 (S1–S12)
	{ name: "Ranked Season 46", short: "Position", value: "SkyWars_skywars_rating_1_20_position" },
	{ name: "Ranked Season 46", short: "Rating", value: "SkyWars_skywars_rating_1_20_rating" },
	{ name: "Ranked Season 47", short: "Position", value: "SkyWars_skywars_rating_2_20_position" },
	{ name: "Ranked Season 47", short: "Rating", value: "SkyWars_skywars_rating_2_20_rating" },
	{ name: "Ranked Season 48", short: "Position", value: "SkyWars_skywars_rating_3_20_position" },
	{ name: "Ranked Season 48", short: "Rating", value: "SkyWars_skywars_rating_3_20_rating" },
	{ name: "Ranked Season 49", short: "Position", value: "SkyWars_skywars_rating_4_20_position" },
	{ name: "Ranked Season 49", short: "Rating", value: "SkyWars_skywars_rating_4_20_rating" },
	{ name: "Ranked Season 50", short: "Position", value: "SkyWars_skywars_rating_5_20_position" },
	{ name: "Ranked Season 50", short: "Rating", value: "SkyWars_skywars_rating_5_20_rating" },
	{ name: "Ranked Season 51", short: "Position", value: "SkyWars_skywars_rating_6_20_position" },
	{ name: "Ranked Season 51", short: "Rating", value: "SkyWars_skywars_rating_6_20_rating" },
	{ name: "Ranked Season 52", short: "Position", value: "SkyWars_skywars_rating_7_20_position" },
	{ name: "Ranked Season 52", short: "Rating", value: "SkyWars_skywars_rating_7_20_rating" },
	{ name: "Ranked Season 53", short: "Position", value: "SkyWars_skywars_rating_8_20_position" },
	{ name: "Ranked Season 53", short: "Rating", value: "SkyWars_skywars_rating_8_20_rating" },
	{ name: "Ranked Season 54", short: "Position", value: "SkyWars_skywars_rating_9_20_position" },
	{ name: "Ranked Season 54", short: "Rating", value: "SkyWars_skywars_rating_9_20_rating" },
	{ name: "Ranked Season 55", short: "Position", value: "SkyWars_skywars_rating_10_20_position" },
	{ name: "Ranked Season 55", short: "Rating", value: "SkyWars_skywars_rating_10_20_rating" },
	{ name: "Ranked Season 56", short: "Position", value: "SkyWars_skywars_rating_11_20_position" },
	{ name: "Ranked Season 56", short: "Rating", value: "SkyWars_skywars_rating_11_20_rating" },
	{ name: "Ranked Season 57", short: "Position", value: "SkyWars_skywars_rating_12_20_position" },
	{ name: "Ranked Season 57", short: "Rating", value: "SkyWars_skywars_rating_12_20_rating" },

	// 2021 (S1–S12)
	{ name: "Ranked Season 58", short: "Position", value: "SkyWars_skywars_rating_1_21_position" },
	{ name: "Ranked Season 58", short: "Rating", value: "SkyWars_skywars_rating_1_21_rating" },
	{ name: "Ranked Season 59", short: "Position", value: "SkyWars_skywars_rating_2_21_position" },
	{ name: "Ranked Season 59", short: "Rating", value: "SkyWars_skywars_rating_2_21_rating" },
	{ name: "Ranked Season 60", short: "Position", value: "SkyWars_skywars_rating_3_21_position" },
	{ name: "Ranked Season 60", short: "Rating", value: "SkyWars_skywars_rating_3_21_rating" },
	{ name: "Ranked Season 61", short: "Position", value: "SkyWars_skywars_rating_4_21_position" },
	{ name: "Ranked Season 61", short: "Rating", value: "SkyWars_skywars_rating_4_21_rating" },
	{ name: "Ranked Season 62", short: "Position", value: "SkyWars_skywars_rating_5_21_position" },
	{ name: "Ranked Season 62", short: "Rating", value: "SkyWars_skywars_rating_5_21_rating" },
	{ name: "Ranked Season 63", short: "Position", value: "SkyWars_skywars_rating_6_21_position" },
	{ name: "Ranked Season 63", short: "Rating", value: "SkyWars_skywars_rating_6_21_rating" },
	{ name: "Ranked Season 64", short: "Position", value: "SkyWars_skywars_rating_7_21_position" },
	{ name: "Ranked Season 64", short: "Rating", value: "SkyWars_skywars_rating_7_21_rating" },
	{ name: "Ranked Season 65", short: "Position", value: "SkyWars_skywars_rating_8_21_position" },
	{ name: "Ranked Season 65", short: "Rating", value: "SkyWars_skywars_rating_8_21_rating" },
	{ name: "Ranked Season 66", short: "Position", value: "SkyWars_skywars_rating_9_21_position" },
	{ name: "Ranked Season 66", short: "Rating", value: "SkyWars_skywars_rating_9_21_rating" },
	{ name: "Ranked Season 67", short: "Position", value: "SkyWars_skywars_rating_10_21_position" },
	{ name: "Ranked Season 67", short: "Rating", value: "SkyWars_skywars_rating_10_21_rating" },
	{ name: "Ranked Season 68", short: "Position", value: "SkyWars_skywars_rating_11_21_position" },
	{ name: "Ranked Season 68", short: "Rating", value: "SkyWars_skywars_rating_11_21_rating" },
	{ name: "Ranked Season 69", short: "Position", value: "SkyWars_skywars_rating_12_21_position" },
	{ name: "Ranked Season 69", short: "Rating", value: "SkyWars_skywars_rating_12_21_rating" },

	// 2022 (S1–S12)
	{ name: "Ranked Season 70", short: "Position", value: "SkyWars_skywars_rating_1_22_position" },
	{ name: "Ranked Season 70", short: "Rating", value: "SkyWars_skywars_rating_1_22_rating" },
	{ name: "Ranked Season 71", short: "Position", value: "SkyWars_skywars_rating_2_22_position" },
	{ name: "Ranked Season 71", short: "Rating", value: "SkyWars_skywars_rating_2_22_rating" },
	{ name: "Ranked Season 72", short: "Position", value: "SkyWars_skywars_rating_3_22_position" },
	{ name: "Ranked Season 72", short: "Rating", value: "SkyWars_skywars_rating_3_22_rating" },
	{ name: "Ranked Season 73", short: "Position", value: "SkyWars_skywars_rating_4_22_position" },
	{ name: "Ranked Season 73", short: "Rating", value: "SkyWars_skywars_rating_4_22_rating" },
	{ name: "Ranked Season 74", short: "Position", value: "SkyWars_skywars_rating_5_22_position" },
	{ name: "Ranked Season 74", short: "Rating", value: "SkyWars_skywars_rating_5_22_rating" },
	{ name: "Ranked Season 75", short: "Position", value: "SkyWars_skywars_rating_6_22_position" },
	{ name: "Ranked Season 75", short: "Rating", value: "SkyWars_skywars_rating_6_22_rating" },
	{ name: "Ranked Season 76", short: "Position", value: "SkyWars_skywars_rating_7_22_position" },
	{ name: "Ranked Season 76", short: "Rating", value: "SkyWars_skywars_rating_7_22_rating" },

	// Kit stats pattern: {stat}_kit_{type}_{mode}_{kit}
	...[
		{
			type: "advanced",
			mode: "solo",
			kits: [
				"armorer",
				"cannoneer",
				"enchanter",
				"enderman",
				"farmer",
				"guardian",
				"hunter",
				"jester",
				"knight",
				"magician",
				"pig-rider",
				"pyro",
				"salmon",
				"slime",
				"sloth",
				"zookeeper",
				"engineer",
			],
		},
		{
			type: "basic",
			mode: "solo",
			kits: [
				"archeologist",
				"armorsmith",
				"baseball-player",
				"batguy",
				"cactus",
				"default",
				"disco",
				"ecologist",
				"energix",
				"fallen-angel",
				"fisherman",
				"frog",
				"grenade",
				"healer",
				"pharaoh",
				"princess",
				"rookie",
				"scout",
				"snowman",
				"speleologist",
				"troll",
				"warlock",
			],
		},
		{ type: "enderchest", mode: "solo", kits: ["enderchest"] },
		{ type: "enderchest", mode: "team", kits: ["enderchest"] },
		{
			type: "defending",
			mode: "team",
			kits: ["armorer", "baseball-player", "batguy", "cactus", "disco", "farmer", "frog", "golem", "guardian"],
		},
		{
			type: "supporting",
			mode: "team",
			kits: [
				"armorsmith",
				"ecologist",
				"enchanter",
				"healer",
				"pharaoh",
				"pyro",
				"princess",
				"rookie",
				"troll",
				"warlock",
				"zookeeper",
			],
		},
		{
			type: "attacking",
			mode: "team",
			kits: [
				"archeologist",
				"enderman",
				"energix",
				"fallen-angel",
				"engineer",
				"fisherman",
				"grenade",
				"hunter",
				"jester",
				"knight",
				"pig-rider",
				"salmon",
				"scout",
				"slime",
				"sloth",
				"snowman",
				"magician",
			],
		},
		{ type: "mining", mode: "team", kits: ["cannoneer", "default", "speleologist"] },
		{
			type: "mythical",
			mode: "",
			kits: ["end-lord", "thundermeister", "cryomancer", "fishmonger", "chronobreaker", "monster-trainer", "nether-lord"],
		},
		{
			type: "mini",
			mode: "solo",
			kits: [
				"armorer",
				"athlete",
				"blacksmith",
				"bowman",
				"champion",
				"healer",
				"hound",
				"magician",
				"paladin",
				"pyromancer",
				"scout",
			],
		},
		{
			type: "ranked",
			mode: "ranked",
			kits: ["default", "champion", "armorer", "athlete", "scout", "pyromancer", "healer", "hound", "magician", "bowman", "paladin"],
		},
		{
			type: "blacksmith",
			mode: "ranked",
			kits: ["blacksmith"],
		},
		{
			type: "mega",
			mode: "mega",
			kits: [
				"armorer",
				"armorsmith",
				"cannoneer",
				"baseball-player",
				"default",
				"enderman",
				"knight",
				"paladin",
				"scout",
				"healer",
				"hellhound",
				"fisherman",
				"hunter",
				"pyromaniac",
				"skeletor",
				"witch",
			],
		},
	].flatMap(({ type, mode, kits }) =>
		kits.flatMap((kit) =>
			["wins", "losses", "kills", "deaths", "time_played", "xp"].map((stat) => {
				const value = `${stat}_kit_${type}${mode ? `_${mode}` : ""}_${kit}`;
				let name;
				if (type == "mini") {
					name = `${toCamelCase(stat)}${type ? ` ${toCamelCase(type)}` : ""} ${toCamelCase(kit.replace(/-/g, " "))}`;
				} else if (type == "mega") {
					name = `${toCamelCase(stat)} Mega ${toCamelCase(kit.replace(/-/g, " "))}`;
				} else if (type == "ranked") {
					name = `${toCamelCase(stat)} Ranked ${toCamelCase(kit.replace(/-/g, " "))}`;
				} else {
					name = `${toCamelCase(stat)}${
						mode ? ` ${toCamelCase(mode === "solo" ? "normal" : mode === "team" ? "insane" : mode)}` : ""
					} ${toCamelCase(kit.replace(/-/g, " "))}`;
				}
				let short: string | undefined;
				switch (stat) {
					case "wins":
						short = "Wins";
						break;
					case "losses":
						short = "Losses";
						break;
					case "kills":
						short = "Kills";
						break;
					case "deaths":
						short = "Deaths";
						break;
					case "xp":
						short = "XP";
						break;
					case "time_played":
						short = "Playtime";
						break;
				}
				return { name, value, short };
			}),
		),
	),
	// Misc stats
	{ name: "SkyWars Experience", value: "skywars_experience", short: "XP" },
	// { name: "SkyWars Level", value: "skywars_experience" },
	{ name: "Coins", value: "coins" },
	{ name: "Heads", value: "heads" },
	{ name: "Kills", value: "kills" },
	{ name: "Deaths", value: "deaths" },
	{ name: "Wins", value: "wins" },
	{ name: "Losses", value: "losses" },
	{ name: "Time Played", value: "time_played" },
	// Game mode stats
	...["solo", "team", "lab"].flatMap((mode) => [
		{ name: `Wins ${mode.charAt(0).toUpperCase() + mode.slice(1)}`, value: `wins_${mode}` },
		{ name: `Losses ${mode.charAt(0).toUpperCase() + mode.slice(1)}`, value: `losses_${mode}` },
		{ name: `Kills ${mode.charAt(0).toUpperCase() + mode.slice(1)}`, value: `kills_${mode}` },
		{ name: `Deaths ${mode.charAt(0).toUpperCase() + mode.slice(1)}`, value: `deaths_${mode}` },
	]),
	...["solo_normal", "solo_insane", "team_normal", "team_insane"].flatMap((mode) => [
		{ name: `Wins ${mode.replace("_", " ").replace(/\b\w/g, (l) => l.toUpperCase())}`, value: `wins_${mode}` },
		{ name: `Losses ${mode.replace("_", " ").replace(/\b\w/g, (l) => l.toUpperCase())}`, value: `losses_${mode}` },
		{ name: `Kills ${mode.replace("_", " ").replace(/\b\w/g, (l) => l.toUpperCase())}`, value: `kills_${mode}` },
		{ name: `Deaths ${mode.replace("_", " ").replace(/\b\w/g, (l) => l.toUpperCase())}`, value: `deaths_${mode}` },
	]),
	// Mini mode only has wins and kills
	{ name: "Wins Mini", value: "wins_mini" },
	{ name: "Kills Mini", value: "kills_mini" },
	{ name: "Games Played Mini", value: "games_mini" },

	//
	{ name: "Survived Players", value: "survived_players" },
	{ name: "Blocks Broken", value: "blocks_broken" },
	{ name: "Blocks Placed", value: "blocks_placed" },
	{ name: "Eggs Thrown", value: "egg_thrown" },
	{ name: "Enderpearls Thrown", value: "enderpearls_thrown" },
	{ name: "Souls Gathered", value: "souls_gathered" },
	{ name: "Souls", value: "souls" },
	{ name: "Opals", value: "opals" },
	{ name: "Soul Well", value: "soul_well" },
	{ name: "Paid Souls", value: "paid_souls" },
	{ name: "Assists", value: "assists" },
	{ name: "Arrows Hit", value: "arrows_hit" },
	{ name: "Arrows Shot", value: "arrows_shot" },
	{ name: "Items Enchanted", value: "items_enchanted" },
	{ name: "Chests Opened", value: "chests_opened" },
	{ name: "Melee Kills", value: "melee_kills" },
	{ name: "Void Kills", value: "void_kills" },
	{ name: "Bow Kills", value: "bow_kills" },
	{ name: "Mob Kills", value: "mob_kills" },
	{ name: "Time Played Solo", value: "time_played_solo" },
	{ name: "Time Played Team", value: "time_played_team" },
	{ name: "Time Played Mega", value: "time_played_mega" },
	{ name: "Time Played Mega Doubles", value: "time_played_mega_doubles" },
	{ name: "Time Played Ranked", value: "time_played_ranked" },
	{ name: "Time Played Lab", value: "time_played_lab" },
	{ name: "Time Played Mini", value: "time_played_mini" },
	{ name: "Kills Lab Solo", value: "kills_lab_solo" },
	{ name: "Deaths Lab Solo", value: "deaths_lab_solo" },
	{ name: "Wins Lab Solo", value: "wins_lab_solo" },
	{ name: "Losses Lab Solo", value: "losses_lab_solo" },
	{ name: "Time Played Lab Solo", value: "time_played_lab_solo" },
	{ name: "Kills Lab Team", value: "kills_lab_team" },
	{ name: "Deaths Lab Team", value: "deaths_lab_team" },
	{ name: "Wins Lab Team", value: "wins_lab_team" },
	{ name: "Losses Lab Team", value: "losses_lab_team" },
	{ name: "Time Played Lab Team", value: "time_played_lab_team" },
	{ name: "Heads Eww", value: "heads_eww" },
	{ name: "Heads Yucky", value: "heads_yucky" },
	{ name: "Heads Meh", value: "heads_meh" },
	{ name: "Heads Decent", value: "heads_decent" },
	{ name: "Heads Salty", value: "heads_salty" },
	{ name: "Heads Tasty", value: "heads_tasty" },
	{ name: "Heads Succulent", value: "heads_succulent" },
	{ name: "Heads Divine", value: "heads_divine" },
	{ name: "Heads Heavenly", value: "heads_heavenly" },
	{ name: "Heads Ethereal", value: "heads_ethereal" },
	{ name: "Heads Indescribable", value: "heads_indescribable" },
	{ name: "Heads Special", value: "heads_special" },
	{ name: "Heads Sweet", value: "heads_sweet" },

	// Heads Solo
	{ name: "Heads Solo", value: "heads_solo" },
	{ name: "Heads Eww Solo", value: "heads_eww_solo" },
	{ name: "Heads Yucky Solo", value: "heads_yucky_solo" },
	{ name: "Heads Meh Solo", value: "heads_meh_solo" },
	{ name: "Heads Decent Solo", value: "heads_decent_solo" },
	{ name: "Heads Salty Solo", value: "heads_salty_solo" },
	{ name: "Heads Tasty Solo", value: "heads_tasty_solo" },
	{ name: "Heads Succulent Solo", value: "heads_succulent_solo" },
	{ name: "Heads Divine Solo", value: "heads_divine_solo" },
	{ name: "Heads Heavenly Solo", value: "heads_heavenly_solo" },
	{ name: "Heads Ethereal Solo", value: "heads_ethereal_solo" },
	{ name: "Heads Indescribable Solo", value: "heads_indescribable_solo" },
	{ name: "Heads Special Solo", value: "heads_special_solo" },
	{ name: "Heads Sweet Solo", value: "heads_sweet_solo" },
	// Heads Team
	{ name: "Heads Team", value: "heads_team" },
	{ name: "Heads Eww Team", value: "heads_eww_team" },
	{ name: "Heads Yucky Team", value: "heads_yucky_team" },
	{ name: "Heads Meh Team", value: "heads_meh_team" },
	{ name: "Heads Decent Team", value: "heads_decent_team" },
	{ name: "Heads Salty Team", value: "heads_salty_team" },
	{ name: "Heads Tasty Team", value: "heads_tasty_team" },
	{ name: "Heads Succulent Team", value: "heads_succulent_team" },
	{ name: "Heads Divine Team", value: "heads_divine_team" },
	{ name: "Heads Heavenly Team", value: "heads_heavenly_team" },
	{ name: "Heads Ethereal Team", value: "heads_ethereal_team" },
	{ name: "Heads Indescribable Team", value: "heads_indescribable_team" },
	{ name: "Heads Special Team", value: "heads_special_team" },
	{ name: "Heads Sweet Team", value: "heads_sweet_team" },
	// Heads Mini
	{ name: "Heads Mini", value: "heads_mini" },
	{ name: "Heads Eww Mini", value: "heads_eww_mini" },
	{ name: "Heads Yucky Mini", value: "heads_yucky_mini" },
	{ name: "Heads Meh Mini", value: "heads_meh_mini" },
	{ name: "Heads Decent Mini", value: "heads_decent_mini" },
	{ name: "Heads Salty Mini", value: "heads_salty_mini" },
	{ name: "Heads Tasty Mini", value: "heads_tasty_mini" },
	{ name: "Heads Succulent Mini", value: "heads_succulent_mini" },
	{ name: "Heads Divine Mini", value: "heads_divine_mini" },
	{ name: "Heads Heavenly Mini", value: "heads_heavenly_mini" },
	{ name: "Heads Ethereal Mini", value: "heads_ethereal_mini" },
	{ name: "Heads Indescribable Mini", value: "heads_indescribable_mini" },
	{ name: "Heads Special Mini", value: "heads_special_mini" },
	{ name: "Heads Sweet Mini", value: "heads_sweet_mini" },

	{ name: "Games Played", value: "games" },
	{ name: "Games Played Solo", value: "games_solo" },
	{ name: "Games Played Team", value: "games_team" },
	{ name: "Games Played Ranked", value: "games_ranked" },
	{ name: "Games Played Mega", value: "games_mega" },
	{ name: "Games Played Mega Doubles", value: "games_mega_doubles" },
	{ name: "Games Played Lab", value: "games_lab" },
	{ name: "Games Played Lab Solo", value: "games_lab_solo" },
	{ name: "Games Played Lab Team", value: "games_lab_team" },

	{ name: "Kills Mega Doubles", value: "kills_mega_doubles" },
	{ name: "Deaths Mega Doubles", value: "deaths_mega_doubles" },
	{ name: "Wins Mega Doubles", value: "wins_mega_doubles" },
	{ name: "Losses Mega Doubles", value: "losses_mega_doubles" },
	{ name: "Kills Ranked", value: "kills_ranked" },
	{ name: "Deaths Ranked", value: "deaths_ranked" },
	{ name: "Wins Ranked", value: "wins_ranked" },
	{ name: "Losses Ranked", value: "losses_ranked" },
	{ name: "Kills Mega", value: "kills_mega" },
	{ name: "Deaths Mega", value: "deaths_mega" },
	{ name: "Wins Mega", value: "wins_mega" },
	{ name: "Losses Mega", value: "losses_mega" },

	{ name: "Potions Brewed", value: "skywars_tonic_taker" },

	{ name: "Wins Lucky Blocks Solo", value: "lab_win_lucky_blocks_lab_solo" },
	{ name: "Wins Lucky Blocks Team", value: "lab_win_lucky_blocks_lab_team" },
	{ name: "Wins Lucky Blocks Lab", value: "lab_win_lucky_blocks_lab" },

	{ name: "Challenge Wins", value: "challenge_wins" },
	{ name: "Challenge Attempts", value: "challenge_attempts" },
	{ name: "1 Challenge Attempts", value: "challenge_attempts_1" },
	{ name: "1 Challenge Wins", value: "challenge_wins_1" },
	{ name: "2 Challenge Attempts", value: "challenge_attempts_2" },
	{ name: "2 Challenge Wins", value: "challenge_wins_2" },
	{ name: "3 Challenge Attempts", value: "challenge_attempts_3" },
	{ name: "3 Challenge Wins", value: "challenge_wins_3" },
	{ name: "4 Challenge Attempts", value: "challenge_attempts_4" },
	{ name: "4 Challenge Wins", value: "challenge_wins_4" },
	{ name: "5 Challenge Attempts", value: "challenge_attempts_5" },
	{ name: "5 Challenge Wins", value: "challenge_wins_5" },
	{ name: "6 Challenge Attempts", value: "challenge_attempts_6" },
	{ name: "6 Challenge Wins", value: "challenge_wins_6" },
	{ name: "7 Challenge Attempts", value: "challenge_attempts_7" },
	{ name: "7 Challenge Wins", value: "challenge_wins_7" },
	{ name: "8 Challenge Attempts", value: "challenge_attempts_8" },
	{ name: "8 Challenge Wins", value: "challenge_wins_8" },
	{ name: "Challenge Attempts Archer", value: "challenge_attempts_archer" },
	{ name: "Challenge Wins Archer", value: "challenge_wins_archer" },
	{ name: "Challenge Attempts Half Health", value: "challenge_attempts_half_health" },
	{ name: "Challenge Wins Half Health", value: "challenge_wins_half_health" },
	{ name: "Challenge Attempts No Block", value: "challenge_attempts_no_block" },
	{ name: "Challenge Wins No Block", value: "challenge_wins_no_block" },
	{ name: "Challenge Attempts No Chest", value: "challenge_attempts_no_chest" },
	{ name: "Challenge Wins No Chest", value: "challenge_wins_no_chest" },
	{ name: "Challenge Attempts Paper", value: "challenge_attempts_paper" },
	{ name: "Challenge Wins Paper", value: "challenge_wins_paper" },
	{ name: "Challenge Attempts Rookie", value: "challenge_attempts_rookie" },
	{ name: "Challenge Wins Rookie", value: "challenge_wins_rookie" },
	{ name: "Challenge Attempts UHC", value: "challenge_attempts_uhc" },
	{ name: "Challenge Wins UHC", value: "challenge_wins_uhc" },
	{ name: "Challenge Attempts Ultimate Warrior", value: "challenge_attempts_ultimate_warrior" },
	{ name: "Challenge Wins Ultimate Warrior", value: "challenge_wins_ultimate_warrior" },

	// Custom leaderboards
	{ name: "Descent Progress", value: "customs_descentProgress" },
	{ name: "Kills Normal", value: "customs_kills_normal" },
	{ name: "Wins Normal", value: "customs_wins_normal" },
	{ name: "Deaths Normal", value: "customs_deaths_normal" },
	{ name: "Losses Normal", value: "customs_losses_normal" },
	{ name: "Kills Insane", value: "customs_kills_insane" },
	{ name: "Wins Insane", value: "customs_wins_insane" },
	{ name: "Deaths Insane", value: "customs_deaths_insane" },
	{ name: "Losses Insane", value: "customs_losses_insane" },
	{ name: "Game Ends Solo", value: "customs_game_ends_solo" },
	{ name: "Kits Max Prestige Normal", value: "customs_kitsMaxPrestigeNormal" },
	{ name: "Kits Max Prestige Insane", value: "customs_kitsMaxPrestigeInsane" },
	{ name: "Kits Max Prestige Mythic", value: "customs_kitsMaxPrestigeMythic" },
	{ name: "Kits Max Prestige Mini", value: "customs_kitsMaxPrestigeMini" },
	{ name: "Kits Max Prestige Mega", value: "customs_kitsMaxPrestigeMega" },
	{ name: "Kits Max Prestige Ranked", value: "customs_kitsMaxPrestigeRanked" },
	{ name: "Kits Max Prestige", value: "customs_kitsMaxPrestige" },

	{ name: "Lab: Rush Wins", value: "lab_win_rush_lab" }, // – Rush Wins
	{ name: "Lab: Rush Solo Wins", value: "lab_win_rush_lab_solo" }, // – Rush Solo Wins
	{ name: "Lab: Rush Team Wins", value: "lab_win_rush_lab_team" }, // – Rush Team Wins
	{ name: "Lab: Slime Wins", value: "lab_win_slime_lab" }, // – Slime Wins
	{ name: "Lab: Slime Solo Wins", value: "lab_win_slime_lab_solo" }, // – Slime Solo Wins
	{ name: "Lab: Slime Team Wins", value: "lab_win_slime_lab_team" }, // – Slime Team Wins
	{ name: "Lab: TNT Madness Wins", value: "lab_win_tnt_madness_lab" },
	{ name: "Lab: TNT Madness Solo Wins", value: "lab_win_tnt_madness_lab_solo" },
	{ name: "Lab: TNT Madness Team Wins", value: "lab_win_tnt_madness_lab_team" },
	{ name: "Lab: Lucky Blocks Wins", value: "lab_win_lucky_blocks_lab" }, // – LB Wins
	{ name: "Lab: Lucky Blocks Solo Wins", value: "lab_win_lucky_blocks_lab_solo" }, // – LB Solo Wins
	{ name: "Lab: Lucky Blocks Team Wins", value: "lab_win_lucky_blocks_lab_team" }, // – LB Team Wins
	{ name: "Lab: Hunters vs Beasts Wins", value: "lab_win_hunters_vs_beasts_lab" }, //
	// { name: "Lab: Hunters vs Beasts Solo Wins", value: "lab_win_hunters_vs_beasts_lab_solo"}, // there is no team, usually solo = overall
];
