// Contains all perks and their lore and stuff
export const perks = {
	solo_bridger: {
		name: "Bridger",
		lore: {
			"0": "§aBridger§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants a §a50% §7chance to not consume",
			"4": "§7§7blocks when placing them.",
			"5": "",
			"6": "§7Rarity: §aCOMMON",
			"7": "",
			"8": "",
		},
		icon: "Oak_Planks.png",
	},
	solo_knowledge: {
		name: "Knowledge",
		lore: {
			"0": "§aKnowledge§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Kills grant §a3 §7EXP Levels.",
			"4": "",
			"5": "§eBig Brain Upgrade",
			"6": "§7§7Kills grant an additional §a+2 §7EXP",
			"7": "§7Levels.",
			"8": "",
			"9": "§7Rarity: §aCOMMON",
			"10": "",
			"11": "",
		},
		icon: "Bottle_o'_Enchanting.png",
	},
	solo_lucky_charm: {
		name: "Lucky Charm",
		lore: {
			"0": "§aLucky Charm§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants a §a30% §7chance to get a §6Golden",
			"4": "§7§6Apple §7on kill.",
			"5": "",
			"6": "§eLuckier Charm Upgrade",
			"7": "§7§7Kills have an additional §a3% §7chance to",
			"8": "§7earn you a §6Golden Apple§7.",
			"9": "",
			"10": "§7Rarity: §aCOMMON",
			"11": "",
			"12": "",
		},
		icon: "Rabbit's_Foot.png",
	},
	solo_mining_expertise: {
		name: "Mining Expertise",
		lore: {
			"0": "§aMining Expertise§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Ores have a §a20% §7chance to drop",
			"4": "§7§7double the materials.",
			"5": "",
			"6": "§eMeticulous Miner Upgrade",
			"7": "§7§7Grants an additional §a+10% §7chance to",
			"8": "§7get double drops from ores.",
			"9": "",
			"10": "§7Rarity: §aCOMMON",
			"11": "",
			"12": "",
		},
		icon: "Iron_Pickaxe.png",
	},
	solo_resistance_boost: {
		name: "Resistance Boost",
		lore: {
			"0": "§aResistance Boost§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants §a15s §7of §9Resistance II §7at the",
			"4": "§7§7start of the game.",
			"5": "",
			"6": "§7Rarity: §aCOMMON",
			"7": "",
			"8": "",
		},
		icon: "Iron_Ingot.png",
	},
	solo_savior: {
		name: "Savior",
		lore: {
			"0": "§aSavior§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Kills grant §a7s §7of §9Absorption I§7.",
			"4": "",
			"5": "§7Rarity: §aCOMMON",
			"6": "",
			"7": "",
		},
		icon: "Golden_Apple.png",
	},
	solo_annoy_o_mite: {
		name: "Annoy-o-mite",
		lore: {
			"0": "§aAnnoy-o-mite§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Bow hits have a §a10% §7chance to spawn",
			"4": "§7§7a §8Silverfish §7next to your enemy.",
			"5": "",
			"6": "§7Rarity: §9RARE",
			"7": "",
			"8": "",
		},
		icon: "Silverfish_Spawn_Egg.png",
	},
	solo_arrow_recovery: {
		name: "Arrow Recovery",
		lore: {
			"0": "§aArrow Recovery§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Bow hits have a §a50% §7chance to give",
			"4": "§7§7you an Arrow back.",
			"5": "",
			"6": "§7Rarity: §9RARE",
			"7": "",
			"8": "",
		},
		icon: "Hopper.png",
	},
	solo_blazing_arrows: {
		name: "Blazing Arrows",
		lore: {
			"0": "§aBlazing Arrows§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Arrows you shoot have a §a15%",
			"4": "§7§a§7chance to light on fire.",
			"5": "",
			"6": "§eSteel Quiver Upgrade",
			"7": "§7§7Arrows you shoot have an additional",
			"8": "§7§a10% §7chance to light on fire.",
			"9": "",
			"10": "§7Rarity: §9RARE",
			"11": "",
			"12": "",
		},
		icon: "Blaze_Powder.png",
	},
	solo_environmental_expert: {
		name: "Environmental Expert",
		lore: {
			"0": "§aEnvironmental Expert§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Reduces §a50% §7of damage taken from",
			"4": "§7§7environmental sources.",
			"5": "",
			"6": "§7Rarity: §9RARE",
			"7": "",
			"8": "",
		},
		icon: "Oak_Sapling.png",
	},
	solo_fat: {
		name: "Fat",
		lore: {
			"0": "§aFat§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants §a20s §7of §9Absorption I §7at the",
			"4": "§7§7start of the game.",
			"5": "",
			"6": "§7Rarity: §9RARE",
			"7": "",
			"8": "",
		},
		icon: "Steak.png",
	},
	solo_speed_boost: {
		name: "Speed Boost",
		lore: {
			"0": "§aSpeed Boost§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants §a300s §7of §9Haste II §7at the start",
			"4": "§7§7of the game.",
			"5": "",
			"6": "§7Rarity: §9RARE",
			"7": "",
			"8": "",
		},
		icon: "Sugar.png",
	},
	solo_barbarian: {
		name: "Barbarian",
		lore: {
			"0": "§aBarbarian§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants a §dSharpness §7level after §a3",
			"4": "§7§a§7kills with an Axe.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
			"9": "",
			"10": "§9+5 Attack Damage",
		},
		icon: "Iron_Axe.png",
	},
	solo_black_magic: {
		name: "Black Magic",
		lore: {
			"0": "§aBlack Magic§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Void kills have a §a30% §7chance to give",
			"4": "§7§7you an §3Ender Pearl§7.",
			"5": "",
			"6": "§eSorcerer's Spell Upgrade",
			"7": "§7§7Void kills have an additional §a5%",
			"8": "§a§7chance to earn you an §3Ender Pearl§7.",
			"9": "",
			"10": "§7Rarity: §6LEGENDARY",
			"11": "",
			"12": "",
		},
		icon: "Cauldron.png",
	},
	solo_frost: {
		name: "Frost",
		lore: {
			"0": "§aFrost§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Bow crits have a §a40% §7chance to",
			"4": "§7§7inflict §a3s §7of §9Slowness I§7.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Snowball.png",
	},
	solo_marksmanship: {
		name: "Marksmanship",
		lore: {
			"0": "§aMarksmanship§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Grants a §dPower §7level after §a2 §7kills",
			"4": "§7§7with a Bow.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Bow.png",
	},
	solo_necromancer: {
		name: "Necromancer",
		lore: {
			"0": "§aNecromancer§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Kills have a §a16% §7chance to spawn a",
			"4": "§7§7friendly §aZombie§7.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Rotten_Flesh.png",
	},
	solo_robbery: {
		name: "Robbery",
		lore: {
			"0": "§aRobbery§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7Melee hits with your fist have a §a20%",
			"4": "§7§a§7chance to steal a held item.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Iron_Bars.png",
	},
	apothecary: {
		name: "Apothecary",
		lore: {
			"0": "§aApothecary§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Positive potion effects have a §a30%",
			"4": "§7§a§7longer duration.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Brewing_Stand.png",
	},
	solo_diamond_in_the_rough: {
		name: "Diamond In The Rough",
		lore: {
			"0": "§aDiamond In The Rough§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Grants a §a25% §7chance to earn a",
			"4": "§7§7§bDiamond §7on kill.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Diamond.png",
	},
	solo_double_edged_sword: {
		name: "Double-Edged Sword",
		lore: {
			"0": "§aDouble-Edged Sword§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Your first §a3 §7Sword kills put a",
			"4": "§7§7§dSharpness §7level on your Sword but",
			"5": "§7§7inflict §c-2 Max ❤§7.",
			"6": "",
			"7": "§7Rarity: §6LEGENDARY",
			"8": "",
			"9": "",
			"10": "",
			"11": "§9+4 Attack Damage",
		},
		icon: "Wooden_Sword.png",
	},
	solo_dragons_pledge: {
		name: "Dragon's Pledge",
		lore: {
			"0": "§aDragon's Pledge§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7An §3Ender Pearl §7replaces the loot in",
			"4": "§7§7one of your island chests. You start",
			"5": "§7§7with only §c7 Max ❤§7.",
			"6": "",
			"7": "§7Rarity: §6LEGENDARY",
			"8": "",
			"9": "",
		},
		icon: "End_Stone.png",
	},
	solo_ender_end_game: {
		name: "Ender End Game",
		lore: {
			"0": "§aEnder End Game§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Refilled chests are §a§a10% §7more likely",
			"4": "§7§7to contain an §3Ender Pearl§7.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "End_Stone.png",
	},
	fortune_teller: {
		name: "Fortune Teller",
		lore: {
			"0": "§aFortune Teller§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Level 2 enchants are guaranteed to",
			"4": "§7§7include §dSharpness I §7or §dProtection I",
			"5": "§7§d§7for Swords and Armor respectively.",
			"6": "",
			"7": "§7Rarity: §6LEGENDARY",
			"8": "",
			"9": "",
		},
		icon: "Enchanting_Table.gif",
	},
	fruit_finder: {
		name: "Fruit Finder",
		lore: {
			"0": "§aFruit Finder§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7The first mid chest you open is",
			"4": "§7§7guaranteed to have a §6Golden Apple§7.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Apple.png",
	},
	hide_and_seek: {
		name: "Hide and Seek",
		lore: {
			"0": "§aHide and Seek§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Earn a Tracking Compass §a30s §7before",
			"4": "§7§7chests refill.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Compass.gif",
	},
	librarian: {
		name: "Librarian",
		lore: {
			"0": "§aLibrarian§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Earn a §dSharpness I§7, §dProtection I§7, or",
			"4": "§7§7§dPower I §7book every §a3 §7kills.",
			"5": "",
			"6": "§7Rarity: §6LEGENDARY",
			"7": "",
			"8": "",
		},
		icon: "Bookshelf.png",
	},
	tenacity: {
		name: "Tenacity",
		lore: {
			"0": "§aTenacity§r",
			"1": "§7§8Perk",
			"2": "",
			"3": "§7§7§7Heal §c1❤ §7after each kill.",
			"4": "",
			"5": "§7Rarity: §6LEGENDARY",
			"6": "",
			"7": "",
		},
		icon: "Magma_Cream.png",
	},
};
